# Generated by Django 3.2.18 on 2023-02-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(db_index=True)),
                ('lexicon', models.CharField(db_index=True, max_length=11)),
                ('word', models.CharField(db_index=True, max_length=255)),
                ('definition', models.TextField()),
            ],
        ),
    ]
