# Generated by Django 3.2.25 on 2026-02-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philolog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='sort_key',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
